FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get install apt-utils -y
RUN apt-get install systemctl git nginx -y
RUN apt-get install vim -y
RUN apt-get update -y
RUN apt-get install python3-dev python3-pip libpq-dev -y
RUN rm -f -- /etc/nginx/sites-enabled/default
RUN pip install uwsgi
CMD [ "bash" ]

# docker build -t randomtools/randomtools-api:init -f Dockerfile.init .


